version: '3.8'

services:
  # Node.js application service
  app:
    image: secureimage
    container_name: node_app
    ports:
      - "7000:80"
    # environment:
    #   - MONGO_URI=mongodb://mongodbcontainer:27017/mongoose_test
    depends_on:
      - mongo
    networks:
      - sarah_network

  # MongoDB service
  mongo:
    image: mongo
    container_name: mongodbcontainer
    ports:
      - "5000:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sarah_network

# Define volumes and networks
volumes:
  mongo-data:

networks:
  sarah_network:
    driver: bridge