apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: http
      port: 5000           # Port exposed inside the cluster
      targetPort: 5000     # Port on the container
      nodePort: 30500      # External port on the node (must be between 30000–32767)
