apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-service-account-binding
  namespace: rbac-lab
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: rbac-lab
roleRef:
  kind: Role
  name: my-service-account
  apiGroup: rbac.authorization.k8s.io
