apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  connection: "bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTcvbW9uZ29vc2VfdGVzdA=="
  TOKEN_SIGNATURE: "YXpvenByb2Zlc3Npb25hbA=="
  BEARER_TOKEN: "QmVhcmVy"
  SALT_ROUND: "OQ=="
  SECRET_KEY: "c2VjcmV0IGtleSAxMjM="
  EMAIL_PASSWORD: "dGtyZSBlZmx2IHF1dHggYWd1aQ=="
  api_key: "NzQzMTc2NjU1NTQ5MTIx"
  api_secret: "a2l4UE1GMEJ5b05waGFtaURkTkFVRTZGUERn"
  CLIENT_ID: "ODI0NzE5MjkwODU0LTRjaXAzamFnM2xqdGRrODZ1Mzh2bmhicnZjcXZ1N25rLmFwcHMuZ29vZ2xlZXNlcmNvbnRlbnQuY29t"
